services:
  postgres:
    image: postgres:15
    container_name: shipment-postgres
    environment:
      POSTGRES_DB: shipment_db
      POSTGRES_USER: shipment_user
      POSTGRES_PASSWORD: shipment_pass
      TZ: UTC
      PGTZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: